development:
  adapter: postgresql
  encoding: unicode
  database: CookItUp_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: CookItUp_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: CookItUp_production
  pool: 5
